### test request
POST http://localhost:9900/order HTTP/1.1
Content-Type: application/json

[
  {
    "id": "0nn534a7-a7c4-48ad-b6ec-7632e36af950",
    "name": "Doggie Soup",
    "prepTime": 5
  },
  {
    "id": "0ff534a7-a7c4-48ad-b6ec-7632e36af950",
    "name": "Cheese Pizza",
    "prepTime": 13
  }
]

### test request without body
GET http://localhost:9900/order HTTP/1.1

### test request
POST http://localhost:9900/order HTTP/1.1
Content-Type: application/json

{
  "id": "0ff534a7-a7c4-48ad-b6ec-7632e36af950",
  "name": "Cheese Pizza",
  "prepTime": 13
}


### test request
POST http://localhost:9900/order HTTP/1.1
Content-Type: application/json

{
  "id": "a8cfcb76-7f24-4420-a5ba-d46dd77bdffd", 
  "name": "Banana Split", 
  "prepTime": 4
}

### test request
POST http://localhost:9900/order HTTP/1.1
Content-Type: application/json

{
    "id": "58e9b5fe-3fde-4a27-8e98-682e58a4a65d", 
    "name": "McFlury", 
    "prepTime": 14
}

### test request
POST http://localhost:9900/order HTTP/1.1
Content-Type: application/json    

{
    "id": "2ec069e3-576f-48eb-869f-74a540ef840c", 
    "name": "Acai Bowl", 
    "prepTime": 12
}